pipeline:
  docker-build-publish:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: truedoctor/rust-wasm
    tags: [ "latest", "1.0", "1.0.4", "nightly-2020-02-28-1" ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

pipeline:
  docker-build:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: truedoctor/rust-wasm
    secrets: [ docker_username, docker_password ]
    when:
      branch:
        exclude: [ master]
