pipeline:
  docker-build-publish:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: truedoctor/rust-wasm
    tags: [ "latest", "1.1", "1.1.9", "nightly" ]
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

pipeline:
  docker-build:
    image: plugins/docker
    dockerfile: Dockerfile
    repo: truedoctor/rust-wasm
    secrets: [ docker_username, docker_password ]
    when:
      branch:
        exclude: [ master]
